### ISSUE TITLE
maxHeapExtractKeyvals: heap underflow

### ISSUE THREAD

**Issue by yannickl96** [GT-TDAlab/dagP#2]
Hello,

when I try to run 
``./exe/rMLGP data/dag_p1.dot 5  --co_norder 8 --write_parts 1``
for the attached .dot file (had to rename it to .txt so GitHub accepts it), I get a "maxHeapExtractKeyvals: heap underflow" error. However, when I re-run the command it suddenly works. Do you have an idea concerning the cause of this problem?

Best,
Yannick
[dag_p1.txt](https://github.com/GT-TDAlab/dagP/files/6785396/dag_p1.txt)

EDIT: From my own debugging I see that https://github.com/GT-TDAlab/dagP/blob/master/src/recBisection/dgraphBisection.c#L359 is the call where the error seems to occur. I don't understand why, though.

**Comment by myozka** [comment]
Thank you, I will have a look at it.

**Comment by myozka** [comment]
Hello,
I have figured out what the problem is and am working on it. The weight distribution over the nodes is highly skewed (heaviest node is 20% of total vertex weight). That affects the stopping and balance criteria hacks for the greedy graph growing algorithm and causes it to go into a corner case. I will push a fix in a couple of days.

In the meantime, you can use the undirected partitioning based (which is default) initial partitioning if that works for your purposes. You should not encounter any problems with that approach.
To do that, you can download metis then un-comment and update the metis-related lines in your `config.py`

**Comment by yannickl96** [comment]
Thank you for your feedback, that helped a lot! From my point of view we can close this issue.

**Comment by myozka** [comment]
Thank you for your patience!

This commit should fix the runtime error for that parameter setting.

Let me know if you have any questions!
